AWSTemplateFormatVersion: "2010-09-09"
Description: MyF0t0 environment setup
Parameters:
  OldPhotoBucketName:
    Type: String
    Description: Enter the Name of an existing S3 bucket that will house photos and thumbnails.  Leave blank to create a new bucket.
    Default: ""
Conditions:
  NewBucket: !Equals [!Ref OldPhotoBucketName, ""]
Resources:
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref AWS::StackName, "ProcessingQueue"]]
  ProcessingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProcessingQueue
      PolicyDocument:
        Statement:
          -
            Action:
              - "SQS:SendMessage"
            Effect: "Allow"
            Resource: !GetAtt ProcessingQueue.Arn
            Principal:
              AWS: "*"

  PhotoBucket:
    Type: AWS::S3::Bucket
    Condition: NewBucket
    DependsOn: ProcessingQueue
    Properties:
      AccessControl: PublicRead
      NotificationConfiguration:
        QueueConfigurations:
          -
            Event: s3:ObjectCreated:*
            Queue: !GetAtt ProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  -
                    Name: "prefix"
                    Value: "img/"
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  MetadataDb:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PK"
          AttributeType: "S"
        -
          AttributeName: "SK"
          AttributeType: "S"
        -
          AttributeName: "GSI1PK"
          AttributeType: "S"
        -
          AttributeName: "GSI1SK"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PK"
          KeyType: "HASH"
        -
          AttributeName: "SK"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "GSI1"
          KeySchema:
            -
              AttributeName: "GSI1PK"
              KeyType: "HASH"
            -
              AttributeName: "GSI1SK"
              KeyType: "RANGE"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
          Projection:
            ProjectionType: "ALL"
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Description: "Execution role for MyF0t0 Lambda functions."
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LambdaExecutionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !GetAtt PhotoBucket.Arn
              - !Join ["", [!GetAtt PhotoBucket.Arn, "/*"]]
          - Effect: Allow
            Action:
              - 'dynamodb:*'
            Resource:
              - !GetAtt MetadataDb.Arn
          - Effect: Allow
            Action:
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteMessage'
              - 'sqs:GetQueueAttributes'
            Resource: !GetAtt ProcessingQueue.Arn
      PolicyName: !Join ["-", [ !Ref AWS::StackName, "lambda-execution"] ]
      Roles:
        - !Ref LambdaRole
  ProcessingFunction:
    Type: AWS::Lambda::Function
    DependsOn: LambdaExecutionPolicy
    Properties:
      Code:
        S3Bucket: myf0t0dist
        S3Key: photo-processor.zip
      Description: Event-driven photo processor
      Environment:
        Variables:
          db_name: !Ref MetadataDb
          photo_bucket: !Ref PhotoBucket
      Handler: photo-processor.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      Timeout: 30
  ProcessingFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeLambda
      FunctionName: !Ref ProcessingFunction
      Principal: sqs.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt ProcessingQueue.Arn
  ProcessingEventSource:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      EventSourceArn: !GetAtt ProcessingQueue.Arn
      FunctionName: !Ref ProcessingFunction
  ApiGatewayRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        -
          PolicyName: ApiGatewayLogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                  - 'logs:GetLogEvents'
                  - 'logs:FilterLogEvents'
                Resource: "*"
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: "*"
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayRole.Arn
  ApiFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: myf0t0dist
        S3Key: api.zip
      Description: MyF0t0 API backend
      Environment:
        Variables:
          db_arn: !Ref MetadataDb
          photo_bucket: !Ref PhotoBucket
      Handler: app.app
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
  ApiFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn: RestApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ApiFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/*/*"
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: "myf0t0"
      Description: "API Gateway for MyF0t0"
  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: LATEST
      Description: Latest Stage
      RestApiId:  !Ref RestApi
      DeploymentId: !Ref ApiDeployment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          DataTraceEnabled: true
          LoggingLevel: INFO
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ProxyRequest
    Properties:
      RestApiId: !Ref RestApi
      StageName: DummyStage
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref RestApi
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: "{proxy+}"
  ProxyRequest:
    Type: AWS::ApiGateway::Method
    DependsOn: ApiFunctionPermission
    Properties:
      RestApiId: !Ref RestApi
      ResourceId: !Ref ProxyResource
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >-
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiFunction.Arn}/invocations
