AWSTemplateFormatVersion: "2010-09-09"
Description: MyF0t0 environment setup
Parameters:
  OldPhotoBucketName:
    Type: String
    Description: Enter the Name of an existing S3 bucket that will house photos and thumbnails.  Leave blank to create a new bucket.
    Default: ""
Conditions:
  NewBucket: !Equals [!Ref OldPhotoBucketName, ""]
Resources:
  PhotoBucke:
    Type: AWS::S3::Bucket
    Condition: NewBucket
    Properties:
      AccessControl: PublicRead
  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  MetadataDb:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "PhotoKey"
          AttributeType: "S"
        -
          AttributeName: "CreationDate"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "PhotoKey"
          KeyType: "HASH"
        -
          AttributeName: "CreationDate"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  DBArnParam:
      Type: AWS::SSM::Parameter
      Properties:
        Name: metadata_db_arn
        Type: String
        Value: !Ref MetadataDb
